# copies the tag from a earlier commit to current commit
# helps with dev release automation (as it should be {current version}-dev)
name: append tag to commit

on:
  push:
    branches:
      - dev
    tags-ignore: 
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          tag=$(git tag | grep -E '^v' | sort -rV | head -n 1)
          if [ -z "$tag" ]; then
            tag="v0.0.0"
          fi
          echo "tag=$tag" >> $GITHUB_OUTPUT
        id: tag
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ steps.tag.outputs.tag }}" 